#!python
from fdfgen import forge_fdf
from character import Character

def fill_pdf(c = Character("Rachel","Barbarian","Dwarf - Hill",{"strength":8,"dexterity":12,"constitution":10,"intelligence":18,"wisdom":14,"charisma":10})):
    fields = [('ClassLevel',c.my_class.class_name+" "+str(c.level)),
              ('CharacterName',c.name),
              ('Background',c.background.name),
              ('Race',c.my_race.name),
              ('STR',c.ability_scores["strength"]),
              ('ProfBonus',c.get_proficiency_bonus()),
              ('AC',c.get_armor_class()),
              ('Speed',c.my_race.base_speed),
              ('PersonalityTraits',c.background.personality_traits),
              ('STRmod',c.get_modifier(c.ability_scores["strength"])),
              ('HPMax',c.get_max_hit_points()),
              ('ST Strength',c.saves["strength"]),
              ('DEX',c.ability_scores["dexterity"]),
              ('DEXmod',c.get_modifier(c.ability_scores["dexterity"])),
              ('ST Dexterity',c.saves["dexterity"]),
              ('CON',c.ability_scores["constitution"]),
              ('CONmod',c.get_modifier(c.ability_scores["constitution"])),
              ('ST Constitution',c.saves["constitution"]),
              ('INT',c.ability_scores["intelligence"]),
              ('INTmod',c.get_modifier(c.ability_scores["intelligence"])),
              ('ST Intelligence',c.saves["intelligence"]),
              ('WIS',c.ability_scores["wisdom"]),
              ('WISmod',c.get_modifier(c.ability_scores["wisdom"])),
              ('ST Wisdom',c.saves["wisdom"]),
              ('CHA',c.ability_scores["charisma"]),
              ('CHAmod',c.get_modifier(c.ability_scores["charisma"])),
              ('ST Charisma',c.saves["charisma"]),
              ('Ideals',c.background.ideals),
              ('Bonds',c.background.bonds),
              ('HDTotal',str(c.level)+"d"+str(c.my_class.hit_die)),
              ('Flaws',c.background.flaws),
              ('Acrobatics',c.skills["acrobatics"]),
              ('Animal',c.skills["animal handling"]),
              ('Athletics',c.skills["athletics"]),
              ('Deception',c.skills["deception"]),
              ('History',c.skills["history"]),
              ('Insight',c.skills["insight"]),
              ('Intimidation',c.skills["intimidation"]),
              ('Investigation',c.skills["investigation"]),
              ('Arcana',c.skills["arcana"]),
              ('Perception',c.skills["perception"]),
              ('Nature',c.skills["nature"]),
              ('Medicine',c.skills["medicine"]),
              ('Religion',c.skills["religion"]),
              ('Stealth',c.skills["stealth"]),
              ('Persuasion',c.skills["persuasion"]),
              ('SleightofHand',c.skills["sleight of hand"]),
              ('Survival',c.skills["survival"]),
              ('Passive',c.get_passive()),
              ('ProficienciesLang',c.get_languages()),
              ('Equipment',c.get_equipment()),
              ('Features and Traits',c.get_features())
              ]
    fdf = forge_fdf("",fields,[],[],[])
    fdf_file = open("data.fdf","wb")
    fdf_file.write(fdf)
    fdf_file.close()
