"""
This file is automatically generated by django.
It's probably a bad idea to mess with it unless we
know what we're doing.
"""

#!/usr/bin/env python
import os
import sys

if __name__ == "__main__":
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "oursite.settings")

    from django.core.management import execute_from_command_line

    execute_from_command_line(sys.argv)
